"""Add FK relationships to demandas

Revision ID: 4a8a7fd18270
Revises: fa226c960aba
Create Date: 2025-11-18 22:19:23.233088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a8a7fd18270'
down_revision: Union[str, None] = 'fa226c960aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demandas', sa.Column('cliente_id', sa.String(length=36), nullable=False))
    op.add_column('demandas', sa.Column('prioridade_id', sa.String(length=36), nullable=False))
    op.drop_index('ix_demandas_prioridade', table_name='demandas')
    op.drop_index('idx_demanda_status_prioridade', table_name='demandas')
    op.create_index('idx_demanda_status_prioridade', 'demandas', ['status', 'prioridade_id'], unique=False)
    op.create_index(op.f('ix_demandas_cliente_id'), 'demandas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_demandas_prioridade_id'), 'demandas', ['prioridade_id'], unique=False)
    op.create_foreign_key(None, 'demandas', 'clientes', ['cliente_id'], ['id'])
    op.create_foreign_key(None, 'demandas', 'tipos_demanda', ['tipo_demanda_id'], ['id'])
    op.create_foreign_key(None, 'demandas', 'secretarias', ['secretaria_id'], ['id'])
    op.create_foreign_key(None, 'demandas', 'prioridades', ['prioridade_id'], ['id'])
    op.drop_column('demandas', 'prioridade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demandas', sa.Column('prioridade', postgresql.ENUM('BAIXA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridadedemanda'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'demandas', type_='foreignkey')
    op.drop_constraint(None, 'demandas', type_='foreignkey')
    op.drop_constraint(None, 'demandas', type_='foreignkey')
    op.drop_constraint(None, 'demandas', type_='foreignkey')
    op.drop_index(op.f('ix_demandas_prioridade_id'), table_name='demandas')
    op.drop_index(op.f('ix_demandas_cliente_id'), table_name='demandas')
    op.drop_index('idx_demanda_status_prioridade', table_name='demandas')
    op.create_index('idx_demanda_status_prioridade', 'demandas', ['status', 'prioridade'], unique=False)
    op.create_index('ix_demandas_prioridade', 'demandas', ['prioridade'], unique=False)
    op.drop_column('demandas', 'prioridade_id')
    op.drop_column('demandas', 'cliente_id')
    # ### end Alembic commands ###
