"""Initial migration: create all tables

Revision ID: fa226c960aba
Revises: 
Create Date: 2025-11-18 22:17:47.697004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa226c960aba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('nome', sa.String(length=200), nullable=False, comment='Nome da empresa/órgão cliente'),
    sa.Column('whatsapp_group_id', sa.String(length=100), nullable=True, comment='ID do grupo WhatsApp (formato: numero@g.us)'),
    sa.Column('trello_member_id', sa.String(length=100), nullable=True, comment='ID do membro no Trello para atribuir cards'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Status ativo/inativo'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_ativo'), 'clientes', ['ativo'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_table('prioridades',
    sa.Column('nome', sa.String(length=50), nullable=False, comment='Nome da prioridade'),
    sa.Column('nivel', sa.Integer(), nullable=False, comment='Nível numérico (1=Baixa, 2=Média, 3=Alta, 4=Urgente)'),
    sa.Column('cor', sa.String(length=7), nullable=False, comment='Cor hexadecimal para UI (ex: #EF4444)'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prioridades_id'), 'prioridades', ['id'], unique=False)
    op.create_index(op.f('ix_prioridades_nivel'), 'prioridades', ['nivel'], unique=False)
    op.create_index(op.f('ix_prioridades_nome'), 'prioridades', ['nome'], unique=True)
    op.create_table('tipos_demanda',
    sa.Column('nome', sa.String(length=100), nullable=False, comment='Nome do tipo de demanda'),
    sa.Column('cor', sa.String(length=7), nullable=False, comment='Cor hexadecimal para UI (ex: #FF5733)'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Status ativo/inativo'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_demanda_ativo'), 'tipos_demanda', ['ativo'], unique=False)
    op.create_index(op.f('ix_tipos_demanda_id'), 'tipos_demanda', ['id'], unique=False)
    op.create_index(op.f('ix_tipos_demanda_nome'), 'tipos_demanda', ['nome'], unique=True)
    op.create_table('secretarias',
    sa.Column('nome', sa.String(length=200), nullable=False, comment='Nome da secretaria/departamento'),
    sa.Column('cliente_id', sa.String(length=36), nullable=False, comment='ID do cliente (FK)'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Status ativo/inativo'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secretarias_ativo'), 'secretarias', ['ativo'], unique=False)
    op.create_index('ix_secretarias_cliente_ativo', 'secretarias', ['cliente_id', 'ativo'], unique=False)
    op.create_index(op.f('ix_secretarias_cliente_id'), 'secretarias', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_secretarias_id'), 'secretarias', ['id'], unique=False)
    op.create_index(op.f('ix_secretarias_nome'), 'secretarias', ['nome'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='Nome de usuário para login (único)'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email do usuário (único)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Senha criptografada com bcrypt'),
    sa.Column('nome_completo', sa.String(length=200), nullable=False, comment='Nome completo do usuário'),
    sa.Column('tipo', sa.Enum('master', 'cliente', name='tipousuario'), nullable=False, comment='Tipo de usuário: master (admin) ou cliente'),
    sa.Column('cliente_id', sa.String(length=36), nullable=True, comment='ID do cliente (NULL para usuários master)'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Se o usuário está ativo no sistema'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_cliente_ativo', 'users', ['cliente_id', 'ativo'], unique=False)
    op.create_index('idx_user_tipo_ativo', 'users', ['tipo', 'ativo'], unique=False)
    op.create_index(op.f('ix_users_ativo'), 'users', ['ativo'], unique=False)
    op.create_index(op.f('ix_users_cliente_id'), 'users', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tipo'), 'users', ['tipo'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('demandas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANDAMENTO', 'AGUARDANDO_CLIENTE', 'CONCLUIDA', 'CANCELADA', name='statusdemanda'), nullable=False),
    sa.Column('prioridade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridadedemanda'), nullable=False),
    sa.Column('prazo_final', sa.Date(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('tipo_demanda_id', sa.String(length=36), nullable=False),
    sa.Column('secretaria_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_demanda_prazo', 'demandas', ['prazo_final', 'status'], unique=False)
    op.create_index('idx_demanda_status_prioridade', 'demandas', ['status', 'prioridade'], unique=False)
    op.create_index('idx_demanda_usuario_status', 'demandas', ['usuario_id', 'status'], unique=False)
    op.create_index(op.f('ix_demandas_id'), 'demandas', ['id'], unique=False)
    op.create_index(op.f('ix_demandas_prioridade'), 'demandas', ['prioridade'], unique=False)
    op.create_index(op.f('ix_demandas_secretaria_id'), 'demandas', ['secretaria_id'], unique=False)
    op.create_index(op.f('ix_demandas_status'), 'demandas', ['status'], unique=False)
    op.create_index(op.f('ix_demandas_tipo_demanda_id'), 'demandas', ['tipo_demanda_id'], unique=False)
    op.create_index(op.f('ix_demandas_usuario_id'), 'demandas', ['usuario_id'], unique=False)
    op.create_table('anexos',
    sa.Column('demanda_id', sa.String(length=36), nullable=False, comment='ID da demanda (FK)'),
    sa.Column('nome_arquivo', sa.String(length=500), nullable=False, comment='Nome original do arquivo'),
    sa.Column('caminho', sa.String(length=1000), nullable=False, comment='Path relativo no servidor (ex: cliente_id/demanda_id/uuid.ext)'),
    sa.Column('tamanho', sa.Integer(), nullable=False, comment='Tamanho do arquivo em bytes'),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False, comment='Tipo MIME (ex: application/pdf, image/jpeg)'),
    sa.Column('trello_attachment_id', sa.String(length=100), nullable=True, comment='ID do anexo no Trello (se foi anexado no card)'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.ForeignKeyConstraint(['demanda_id'], ['demandas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anexos_demanda_id'), 'anexos', ['demanda_id'], unique=False)
    op.create_index(op.f('ix_anexos_id'), 'anexos', ['id'], unique=False)
    op.create_index('ix_anexos_tipo_mime', 'anexos', ['tipo_mime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anexos_tipo_mime', table_name='anexos')
    op.drop_index(op.f('ix_anexos_id'), table_name='anexos')
    op.drop_index(op.f('ix_anexos_demanda_id'), table_name='anexos')
    op.drop_table('anexos')
    op.drop_index(op.f('ix_demandas_usuario_id'), table_name='demandas')
    op.drop_index(op.f('ix_demandas_tipo_demanda_id'), table_name='demandas')
    op.drop_index(op.f('ix_demandas_status'), table_name='demandas')
    op.drop_index(op.f('ix_demandas_secretaria_id'), table_name='demandas')
    op.drop_index(op.f('ix_demandas_prioridade'), table_name='demandas')
    op.drop_index(op.f('ix_demandas_id'), table_name='demandas')
    op.drop_index('idx_demanda_usuario_status', table_name='demandas')
    op.drop_index('idx_demanda_status_prioridade', table_name='demandas')
    op.drop_index('idx_demanda_prazo', table_name='demandas')
    op.drop_table('demandas')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tipo'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cliente_id'), table_name='users')
    op.drop_index(op.f('ix_users_ativo'), table_name='users')
    op.drop_index('idx_user_tipo_ativo', table_name='users')
    op.drop_index('idx_user_cliente_ativo', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_secretarias_nome'), table_name='secretarias')
    op.drop_index(op.f('ix_secretarias_id'), table_name='secretarias')
    op.drop_index(op.f('ix_secretarias_cliente_id'), table_name='secretarias')
    op.drop_index('ix_secretarias_cliente_ativo', table_name='secretarias')
    op.drop_index(op.f('ix_secretarias_ativo'), table_name='secretarias')
    op.drop_table('secretarias')
    op.drop_index(op.f('ix_tipos_demanda_nome'), table_name='tipos_demanda')
    op.drop_index(op.f('ix_tipos_demanda_id'), table_name='tipos_demanda')
    op.drop_index(op.f('ix_tipos_demanda_ativo'), table_name='tipos_demanda')
    op.drop_table('tipos_demanda')
    op.drop_index(op.f('ix_prioridades_nome'), table_name='prioridades')
    op.drop_index(op.f('ix_prioridades_nivel'), table_name='prioridades')
    op.drop_index(op.f('ix_prioridades_id'), table_name='prioridades')
    op.drop_table('prioridades')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_ativo'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
